spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./h2db/sampledb;MODE=PostgreSQL
    username: username
    password: password

server:
  port: 8080

app:
  execute:
    user: 
  google:
    oauth2-url: 
    api-url: 
    sheet-id: 
    client-id: 
    client-secret: 
    refresh-token: 
